name: IP Filter Automation

on:
  push:
    branches: [ main ]
    paths:
      - 'bad_ips'
 # schedule:
  #  - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  filter-ips:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      # 新增：检查根目录文件，确认fgrb.py存在（用于调试）
      - name: Verify Script Exists
        run: |
          echo "当前目录文件列表："
          ls -la  # 列出根目录所有文件，查看fgrb.py是否在列
          echo "检查fgrb.py是否存在："
          if [ -f "fgrb.py" ]; then echo "✅ fgrb.py 存在"; else echo "❌ fgrb.py 不存在"; fi

      # 执行脚本：确保文件名是fgrb.py
      - name: Run IP Filter Script
        run: python fgrb.py

      - name: Check for Changes
        id: check_changes
        run: |
          git status --porcelain
          echo "changes=$(git status --porcelain | wc -l)" >> $GITHUB_OUTPUT

      - name: Commit and Push Changes
        if: steps.check_changes.outputs.changes > 0
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add good_ips
          git commit -m "Auto-filter IPs: Remove bad entries [skip ci]"
          git push origin main
