name: update Dynv6&Dynu A

on:
  schedule:
    - cron: '0 */3 * * *' # 每3小时运行一次
  workflow_dispatch: # 允许手动触发

jobs:

  update-all:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        pip install requests
        
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 0
        keep_minimum_runs: 4
        
    - name: Run script 
      env:
        DYNV6_TOKEN: ${{ secrets.DYNV6_TOKEN }}
        QQ_771_TOKEN: ${{ secrets.QQ_771_TOKEN }}
        DYNU_TOKEN: ${{ secrets.DYNU_TOKEN }}
        LIVE_CFV_TOKEN: ${{ secrets.LIVE_CFV_TOKEN }}
      run: |
        python ${{ github.workspace }}/my_self.py
        
    - name: Commit and push changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Action"
        if [ -n "$(git status --porcelain)" ]; then
          git add docs/index.html docs/qq docs/live docs/index5 docs/index10 docs/index15 docs/index20 docs/index25 docs/index30 docs/index35 docs/index40 docs/index45 docs/index50 docs/index55 docs/index60 docs/qq5 docs/qq10 docs/qq15 docs/qq20 docs/qq25 docs/qq30 docs/live5 docs/live10 docs/live15
          git commit -m "Automatic update"
          git commit -m "Automatic update"
          git push
        else
          echo "No changes detected, skipping commit."
        fi
